### PR TITLE
SQLite query for hidden gems

### PR DESCRIPTION
**Pull request by woctezuma**
Let me know whether it works. I don't know SQL and I have no idea how to test the code.

### CODE REVIEW

**Comment by Bilge** [comment]
Fantastic, I'll try it out and post the results.

**Comment by Bilge** [comment]
`pow(10, 6.42) === 2630268`, not `2630000`. Is there some reason why this value has been rounded to 3 s.f.?

**Comment by Bilge** [comment]
Unfortunately the query fails with the following error and I'm currently unsure why.

>  SQLSTATE[HY000]: General error: 1 near "+": syntax error

**Comment by Bilge** [comment]
@woctezuma OK, I fixed it. Does [this list](http://gems.steam250.com/hidden_gems.html) look correct?

**Comment by woctezuma** [comment]
Yes, this ranking looks good: at first sight, it is the same as [the ranking](https://gist.github.com/woctezuma/ef247801af2f8884a986b49fcfa7b3a3) which I get after running the algorithm with today's data.

As for the rounding of the parameter to 3 significant digits, there is no point in being extra precise: this parameter is just obtained as the result of an optimization, and it is homogeneous to a number of players, so weighting with 2.63 million or 2.630268 million... should not matter too much.

**Comment by Bilge** [comment]
Excellent. Do you require any changes to the page or are you happy for it to go live as is?

**Comment by woctezuma** [comment]
When the algorithm was discussed on [PC Gamer](https://www.pcgamer.com/this-algorithm-picks-out-steams-best-hidden-gems/), it appeared some people did not like the amount of anime games in the ranking, and it is a limitation of my method: I cannot distinguish between _hidden gems_ and _appreciated niche games_. To try to alleviate this issue, I used to filter the ranking with genres or tags (remove anime, or remove early access, focus on rogue-like, etc.), but this is not possible anymore because SteamSpy now only provides tags for queries for individual games.

So, I'm happy with the current page, I think it is the best we can do, we just have to acknowledge the aforementioned limitation.

**Comment by Bilge** [comment]
I can get the tags and filter out anime if that's what you want.

**Comment by woctezuma** [comment]
Some people would prefer to have anime or other genres, for instance puzzle ; other people won't. In the end, it is too subjective. Ideally, niche genres could be identified and it could be suggested to filter out some of these genres (but it would be up to the reader to select which genre to filter). However, for now, I think it is best to leave the ranking as it is, and keep this limitation of the method in mind.

**Comment by woctezuma** [comment]
Yes, I agree. I used to filter out:

- "Visual Novel"
- "Anime"
- "Otome"

Some people might want to filter out these too:

- "Early Access"
- "VR"
- "Free to Play"
- "Touch-Friendly"
- "Text-Based"

**Comment by Bilge** [comment]
I don't feel like it's necessary to filter out *anime*; *visual novel* will catch most of those anyway. Non-novel anime games should be fine.

**Comment by woctezuma** [comment]
True.

**Comment by woctezuma** [comment]
By the way, let me know if I can share the link to this ranking of hidden gems.

**Comment by Bilge** [comment]
I guess you can, this is a public forum after all, but it was intended to be for your eyes only. In any case, the link is only temporary; why not wait until it goes live tomorrow? Who do you wish to share it with?

**Comment by woctezuma** [comment]
It is fine: I will wait until it is live before sharing the link here and there. It is just that I like my ranking. :)

**Comment by Bilge** [comment]
Let's chat offline. Do you have a preferred IM application?

**Comment by woctezuma** [comment]
I have Discord, is that fine?

**Comment by Bilge** [comment]
Sure.

**Comment by woctezuma** [comment]
If you want, you can contact me through the channel of SerpentAI [on Discord](https://discord.gg/9D5SuxH).

**Pull request merged**
